version: '3.9'
networks:
  default:
    ipam:
      config:
        - subnet: 10.89.0.0/24
services:
  #######################################################
  #-----------------------------------------------------#
  #                       MEDIA                         #
  #-----------------------------------------------------#
  #######################################################
  audiobookshelf:
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    volumes:
      - ${SSD1}/media/audio/audiobooks/audiobookshelf:/audiobooks:z
      - ${SSD1}/media/audio/podcasts/audiobookshelf:/podcasts:z
      - ./volumes/media/audiobookshelf/config:/config:z
      - ./volumes/media/audiobookshelf/metadata:/metadata:z
    environment:
      - TZ=${TZ}
    restart: unless-stopped

  jellyfin:
    container_name: jellyfin
    image: docker.io/jellyfin/jellyfin:latest
    environment:
      - TZ=${TZ}
    volumes:
      - ./volumes/media/jellyfin:/config:z
      - ${SSD2}/shows:/data/tvshows:z
      - ${SSD1}/media/video/films:/data/movies:z
      - ${SSD1}/media/audio/music:/data/music:z
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=homelab_default"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAIN}`)"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.services.jellyfin.loadbalancer.server.url=http://10.89.0.3:8096"
      - "traefik.http.routers.jellyfin-docker.priority=10"  # Low
    ports:
      - 127.0.0.1:8096:8096
      - 127.0.0.1:8920:8920
      - 127.0.0.1:1900:1900/udp
    networks:
      default:
        ipv4_address: 10.89.0.3
    restart: unless-stopped

  jellyfin-meilisearch:
     container_name: jellyfin-meilisearch
     image: docker.io/getmeili/meilisearch:latest
     environment:
       MEILI_ENV: production
       MEILI_NO_ANALYTICS: "true"
       MEILI_MASTER_KEY: ${JF_MEILI_MASTER_KEY}
     volumes:
       # meilisearch's data
       - ./volumes/media/jellyfin/meilisearch/data:/meili_data:z
     ports:
       - 7700:7700
     restart: unless-stopped

  #kavita:

  kiwix:
    container_name: kiwix
    image: ghcr.io/kiwix/kiwix-serve
    volumes:
      - ${SSD1}/media/sites/zim:/data:z
    ports:
      - '39237:8080'
    command: '*.zim'
    restart: unless-stopped

  #miniflux:

  #navidrome:

  readeck:
    container_name: readeck
    image: codeberg.org/readeck/readeck:latest
    volumes:
      - ./volumes/media/readeck:/readeck:z
    ports:
      - 36787:8000
    restart: unless-stopped

  #romm:

  #romm:
  
  #tubearchivist:

  #######################################################
  #-----------------------------------------------------#
  #                         ARR                         #
  #-----------------------------------------------------#
  #######################################################

  audiobookrequest:
    container_name: audiobookrequest
    image: docker.io/markbeep/audiobookrequest:latest
    environment:
      - TZ=${TZ}
    ports:
      - 35667:8000
    volumes:
      - ./volumes/arr/audiobookrequest:/config:z

  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./volumes/arr/bazarr/config:/config:z
      - ${SSD2}/shows:/tv:z
      - ${SSD1}/media/video/films:/movies:z
    ports:
      - 6767:6767
    restart: unless-stopped

  #monochrome:
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./volumes/arr/prowlarr/data:/config:z
    ports:
      - 9696:9696
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    security_opt:
      - label=disable
    volumes:
      - ./volumes/arr/radarr/data:/config:z
      - ${SSD1}/media/video/films:/movies:z
      - ${SSD1}/media/video/films/.downloads:/downloads:z
    ports:
      - 7878:7878
    restart: unless-stopped

  seerr:
    container_name: seerr
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
      - PORT=5055
    ports:
      - 5055:5055
    volumes:
      - ./volumes/seerr/config:/app/config:z
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped

  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    security_opt:
      - label=disable
    volumes:
      - ./volumes/arr/sonarr/data:/config:z
      - ${SSD2}/shows:/tv:z
      - ${SSD2}/shows/.downloads:/downloads:z
    ports:
      - 8989:8989
    restart: unless-stopped
  #soulsolid:

  #######################################################
  #-----------------------------------------------------#
  #                     PRODUCTIVITY                    #
  #-----------------------------------------------------#
  #######################################################

  #beaver:
  #siyuan:
  #solidtime:
  #wakapi:
  
  #######################################################
  #-----------------------------------------------------#
  #                      SERVICES                       #
  #-----------------------------------------------------#
  #######################################################

  #algernon:
  #archivebox:
  #cookcli:
  #karoake-eternal:
  #pdfding:
  #reactive-resume:
  #searxng:
  #wingfit:
  
  #######################################################
  #-----------------------------------------------------#
  #                      FINANCES                       #
  #-----------------------------------------------------#

  #sure:
  #wallos:

  #######################################################

  #######################################################
  #-----------------------------------------------------#
  #                       TOOLS                         #
  #-----------------------------------------------------#
  #######################################################

  it-tools:
    container_name: it-tools
    image: docker.io/corentinth/it-tools:latest
    ports:
      - 40661:80
    restart: unless-stopped

  languagetool:
    container_name: languagetool
    image: docker.io/erikvl87/languagetool
    environment:
      - langtool_languageModel=/ngrams   # OPTIONAL: Using ngrams data
      - Java_Xms=512m                    # OPTIONAL: Setting a minimal Java heap size of 512 mib
      - Java_Xmx=1g                      # OPTIONAL: Setting a maximum Java heap size of 1 Gib
    volumes:
      - ./volumes/tools/languagetool/ngrams/data:/ngrams:z     # OPTIONAL: The location of ngrams data on the local machine
      - ./volumes/tools/languagetool/logback.xml:/LanguageTool/logback.xml:ro,z  # OPTIONAL: Overwrite the logging configuration
    ports:
      - 8010:8010
    restart: unless-stopped

  morphos:
    container_name: morphos
    image: ghcr.io/danvergara/morphos-server:latest
    ports:
      - 33245:8080
    restart: unless-stopped

  myip:
    container_name: myip
    image: docker.io/jason5ng32/myip:latest
    ports:
      - 18966:18966
    restart: always

  omni-tools:
    container_name: omni-tools
    image: docker.io/iib0011/omni-tools:latest
    ports:
      - 37799:80
    restart: unless-stopped

  watchyourlan:
    container_name: watchyourname
    image: docker.io/aceberg/watchyourlan:latest
    environment:
      TZ: ${TZ}               # required: needs your TZ for correct time
      IFACES: "enp4s0 wlxf4ec3892dd51"  # required: 1 or more interface
    volumes:
      - ~/.dockerdata/wyl:/data/WatchYourLAN
    ports:
      - 8850:8850
    network_mode: host      
    restart: unless-stopped

  #######################################################
  #-----------------------------------------------------#
  #                      STORAGE                        #
  #-----------------------------------------------------#
  #######################################################
  #copyparty:

  immich:
    container_name: immich
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/data:z
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - immich-redis
      - immich-db
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich-machine-learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://docs.immich.app/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - ./volumes/storage/immich/model-cache:/cache:z
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  immich-redis:
    container_name: immich-redis
    image: docker.io/valkey/valkey:9@sha256:546304417feac0874c3dd576e0952c6bb8f06bb4093ea0c9ca303c73cf458f63
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  immich-db:
    container_name: immich-db
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    environment:
      POSTGRES_PASSWORD: ${IMMICH_DB_PASSWORD}
      POSTGRES_USER: ${IMMICH_DB_USERNAME}
      POSTGRES_DB: ${IMMICH_DB_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${IMMICH_DB_DATA_LOCATION}:/var/lib/postgresql/data:z
    shm_size: 128mb
    healthcheck:
      disable: false
    restart: always
  
  #papra:
  #syncthing:

  #######################################################
  #-----------------------------------------------------#
  #                      TRACKING                       #
  #-----------------------------------------------------#
  #######################################################
  #adventurelog:
  #airtrail:
  #dawarich:
  #lubelogger:
  #traccar:
  #yamtrack:

  #######################################################
  #-----------------------------------------------------#
  #                     NETWORKING                      #
  #-----------------------------------------------------#
  #######################################################
  #adguardhome:
  cloudflared:
    container_name: cloudflared
    image: docker.io/cloudflare/cloudflared:latest
    network_mode: host
    command: tunnel --config /etc/cloudflared/config.yml run lab-tunnel
    #command: tunnel --no-autoupdate run lab-tunnel
    volumes:
      - ./volumes/networking/cloudflared:/etc/cloudflared:z
    restart: unless-stopped

  flaresolverr:
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    environment:
      - LOG_LEVEL=info
    ports:
      - 8191:8191
    restart: unless-stopped

  gluetun:
    container_name: gluetun
    image: docker.io/qmcgaw/gluetun:latest
    security_opt:
      - label=disable
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=windscribe
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=cKfLZjeQdMyLZQwbSHNA6ENWlvzFvl62yC2xHlDuInw=
      - WIREGUARD_PUBLIC_KEY=7LiZu9B4qzVwl3jKRVs7ivx/BHi/jnSS/GWSuxEClgk=
      - WIREGUARD_PRESHARED_KEY=3YK70QNSH4hQBiO8jRHQEllhpIXcosu/bPmL+IzDsKE=
      - WIREGUARD_ADDRESSES=100.122.11.72/32
      - SERVER_REGIONS=us east
      - UPDATER_PERIOD=
      - HTTPPROXY=on
      - HTTPPROXY_LISTENING_ADDRESS=:8888
      #- HTTPPROXY_USER=myuser        # optional but recommended
      #- HTTPPROXY_PASSWORD=mypass    # optional but recommended
    volumes:
      - ./volumes/networking/gluetun:/gluetun:z
    ports:
      - 44001:44001 # Qbittorent
      - 8888:8888/tcp   # HTTP proxy
    restart: always

  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - WEBUI_PORT=44001
    security_opt:
      - label=disable
    volumes:
      - ./volumes/networking/qbittorrent/config:/config:z
      - ${SSD2}/shows/.downloads:/downloads/tv-sonarr:z
      - ${SSD1}/media/video/films/.downloads:/downloads/movies-radarr:z
    network_mode: "container:gluetun"
    depends_on:
      - gluetun
    restart: unless-stopped

  traefik:
    container_name: traefik
    image: docker.io/traefik:latest
    command: |
      --providers.docker=true
      --providers.docker.exposedbydefault=false
      --providers.docker.network=homelab_default
      --providers.file.directory=/dynamic
      --providers.file.watch=true
      --entrypoints.web.address=:8000
      --entrypoints.websecure.address=:8443
      --certificatesresolvers.cloudflare.acme.email=${CLOUDFLARE_ACME_EMAIL}
      --certificatesresolvers.cloudflare.acme.dnschallenge=true
      --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      --api.insecure=true
      --api.dashboard=true
      --accesslog=true
      --log.level=DEBUG
    labels:
      - "traefik.enable=true"
    security_opt:
      - label=disable
    volumes:
      - ./volumes/networking/traefik/dynamic:/dynamic:ro,z
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock:z
    ports:
      - "8443:8443"  # 0.0.0.0 not 127.0.0.1
      - "8000:8000"
      - "8080:8080"
    networks:
      default:
    restart: always
  
  #######################################################
  #-----------------------------------------------------#
  #                     MONITORING                      #
  #-----------------------------------------------------#
  #######################################################
  #prometheus:
  #glance:
  #grafana:
  mafl:
    container_name: mafl # change as needed
    image: docker.io/hywax/mafl
    ports:
      - '3000:3000'
    volumes:
      - ./volumes/monitoring/mafl:/app/data:z
    restart: unless-stopped
  #tracearr:
  #uptime-kuma:

  #######################################################
  #-----------------------------------------------------#
  #                      SECURITY                       #
  #-----------------------------------------------------#
  #######################################################
  #aliasvault:
  #authentik:
  #  container_name: authentik
  #  image: ghcr.io/goauthentik/server:latest
  #  command: server
  #  labels:
  #    - "traefik.enable=true"
  #    - "traefik.http.routers.authentik.rule=Host(`auth.${DOMAIN}`)"  # Your Authentik domain
  #    - "traefik.http.routers.authentik.entrypoints=websecure"
  #    - "traefik.http.routers.authentik.tls.certresolver=cloudflare"  # Matches your Traefik command
  #    - "traefik.http.services.authentik.loadbalancer.server.port=9000"
  #  environment:
  #    AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
  #    AUTHENTIK_REDIS__HOST: authentik-redis
  #    AUTHENTIK_POSTGRESQL__HOST: authentik-db
  #    AUTHENTIK_POSTGRESQL__USER: admin
  #    AUTHENTIK_POSTGRESQL__NAME: admin
  #    AUTHENTIK_POSTGRESQL__PASSWORD: ${AUTHENTIK_DB_PASSWORD}
  #    AUTHENTIK_BOOTSTRAP_EMAIL: ${AUTHENTIK_BOOSTRAP_EMAIL}
  #    AUTHENTIK_BOOTSTRAP_PASSWORD: ${AUTHENTIK_BOOTSTRAP_PASSWORD}
  #  volumes:
  #    - ./volumes/security/authentik/media:/media:z
  #    - /run/user/1000/podman/podman.sock:/var/run/docker.sock:z
  #  depends_on:
  #    - authentik-db
  #    - authentik-redis
  #  restart: unless-stopped

  #authentik-db:
  #  container_name: authentik-db
  #  image: docker.io/postgres:16-alpine
  #  environment:
  #    POSTGRES_USER: admin
  #    POSTGRES_DB: admin
  #    POSTGRES_PASSWORD: ${AUTHENTIK_DB_PASSWORD}
  #  volumes: 
  #    - ./volumes/security/authentik/db:/var/lib/postgresql/data:z
  #  restart: unless-stopped

  #authentik-proxy:
  #  container_name: authentik-proxy
  #  image: ghcr.io/goauthentik/proxy:latest
  #  environment:
  #    AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
  #    AUTHENTIK_TOKEN: ${AUTHENTIK_OUTPOST_TOKEN}
  #    AUTHENTIK_HOST: https://auth.${DOMAIN}
  #    AUTHENTIK_ERROR_REPORTING__ENABLED: "true"
  #  labels:
  #    - "traefik.enable=true"
  #  restart: unless-stopped

  #authentik-redis:
  #  container_name: authentik-redis
  #  image: docker.io/redis:7-alpine
  #  volumes: 
  #    - ./volumes/security/authentik/redis:/data:z
  #  restart: unless-stopped

  #authentik-worker:
  #  container_name: authentik-worker
  #  image: ghcr.io/goauthentik/server:latest
  #  command: worker
  #  environment:
  #    AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
  #    AUTHENTIK_REDIS__HOST: authentik-redis
  #    AUTHENTIK_POSTGRESQL__HOST: authentik-db
  #    AUTHENTIK_POSTGRESQL__USER: admin
  #    AUTHENTIK_POSTGRESQL__NAME: admin
  #    AUTHENTIK_POSTGRESQL__PASSWORD: ${AUTHENTIK_DB_PASSWORD}
  #    AUTHENTIK_BOOTSTRAP_EMAIL: ${AUTHENTIK_BOOSTRAP_EMAIL}
  #    AUTHENTIK_BOOTSTRAP_PASSWORD: ${AUTHENTIK_BOOTSTRAP_PASSWORD}
  #  volumes: 
  #    - ./volumes/security/authentik/media:/media:z
  #  depends_on:
  #    - authentik-db
  #    - authentik-redis
  #  restart: unless-stopped
